### ISSUE TITLE
Andy hello

### ISSUE THREAD

**Issue by cplusplus714** [andyfmiller/LtiLibrary.Owin#7] opened 2016-07-09 02:06 UTC
I have a question/issue about posting grades for all students, I tried to reach out on your blog and Moodle forum. 

Help is needed. 

I am trying to use LtiLibrary and post grades to all students under LTI item in the gradebook in Moodle.

For now, I can post only grade for a student that click on the LTI like so,

var result=LtiLibrary.Core.Outcomes.v1.OutcomesClient.PostScore(Request.Form["lis_outcome_service_url"].ToString(), Request.Form["oauth_consumer_key"].ToString(), 
ConfigurationManager.AppSettings["SharedSecret"].ToString(), Request.Form["lis_result_sourcedid"].ToString(), 0.40);

The question is how can I post grade for a student with id 22 (for example), my id is 35 and I am trying to replace it, like so...but it does not allow me to post grade . Any ideas?

var result=LtiLibrary.Core.Outcomes.v1.OutcomesClient.PostScore(Request.Form["lis_outcome_service_url"].ToString(), Request.Form["oauth_consumer_key"].ToString(), 
ConfigurationManager.AppSettings["SharedSecret"].ToString(), Request.Form["lis_result_sourcedid"].ToString().Replace("\"userid\":\"35\"", "\"userid\":\"22\""), 0.40);

**Comment by andyfmiller** [comment] 2016-07-10 15:37
I do something similar in my [Consumer](http://consumer.azurewebsites.net/)/[Provider ](http://provider.azurewebsites.net/)samples, so it should be possible with Moodle...in theory at least.

Although I am not familiar with Moodle, my guess is that Moodle is preventing one student from posting outcomes for a different student. At least I would do that if I were Moodle.

You might try launching your tool as one of the teachers for course in Moodle.

I hope that helps. If not, I think the folks over at Moodle will have better suggestions since they know the Moodle.

**Comment by cplusplus714** [comment] 2016-07-10 15:54
Thanks I did posted on Moodle forum as well. No reply so far.

And also opened the LTI link as a teacher. It does not update score for a different student.

**Comment by andyfmiller** [comment] 2016-07-10 15:59
Since LtiLibrary is such a thin layer over the LTI spec, and samples built with the LtiLibrary pass the LTI certification tests, I don't think the problem is in LtiLibrary. Moodle must not like the data you are passing. I'm afraid I don't know anything about Moodle and cannot help you.

**Comment by cplusplus714** [comment] 2016-07-10 16:03
ok, thanks. Last question, how to see the error message after posting grades?

**Comment by andyfmiller** [comment] 2016-07-10 16:12
If the Tool Consumer includes an error message in its response, it will be in the BasicResult that is returned by PostScore (see BasicResult.Message).

**Comment by cplusplus714** [comment] 2016-07-15 19:07
Andy it's me again.
Is there the library function to get lis_result_sourcedid for all students from Moodle?

**Comment by andyfmiller** [comment] 2016-07-30 18:30
No there isn't. The library is a pretty thin layer over the IMS spec, and that function is not included in the spec. It is up to the tool provider to keep track of the lis_result_sourcedid and lis_outcome_service_url for each launch and then use the appropriate values when sending outcomes.

**Closed** 2016-10-08 22:34 UTC
